### ISSUE TITLE
Fix arguments to ls and ps on Mac

### ISSUE THREAD

**Issue by be-rock** [sustrik/uxy#9]
This project has incredible potential but having some setup issues.  i tried cloning the repo and putting `uxy` on my `PATH` (Mac OS) but seeing some issues:

```
$ uxy ls
TYPE PERMISSIONS LINKS OWNER      GROUP      SIZE         TIME                                  NAME
ls: illegal option -- N
usage: ls [-ABCFGHLOPRSTUWabcdefghiklmnopqrstuwx1] [file ...]
```

```
$ uxy ps
PID      TTY      TIME       CMD
ps: illegal option -- -
usage: ps [-AaCcEefhjlMmrSTvwXx] [-O fmt | -o fmt] [-G gid[,gid...]]
          [-g grp[,grp...]] [-u [uid,uid...]]
          [-p pid[,pid...]] [-t tty[,tty...]] [-U user[,user...]]
       ps [-L]
```

**Comment by sustrik** [comment]
Yeah, I've written it on Linux and adjusted the options to the linux version of `ls`. The versin of OSX has different parameters. I'll try to fix it, but I don't have a Mac, so I won't be able to test it. If you want to contribute, look at this line: https://github.com/sustrik/uxy/blob/master/uxy#L714

You can try to modify the parameters so that they work well with Mac version of ls.

**Comment by be-rock** [comment]
Great, thank you, will try to take a look when free time arises.  Can you please add a "good first issue" label to this Issue as well?

**Comment by sustrik** [comment]
Done.

**Comment by sustrik** [comment]
MacOSX tests now run (and fail) on Travis CI: https://travis-ci.org/sustrik/uxy
